#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Kyoro-HealthHub contributors
"""
PEM Evidence Score — Analyse und Visualisierung

Liest aus pem_evidence_scores (erzeugt von compute_pem.py) und zeigt:
  - Score-Zeitreihe mit Infektions-Cutoff (vor/nach)
  - Recovery-Pattern-Verteilung (Sport vs. PEM)
  - Monatliche PEM-Burden (analog zu AFib-Burden)
  - Sport-bereinigte PEM-Rate vor/nach Infektion

@tier        calibrated
@purpose.de  Liest aus pem_evidence_scores (erzeugt von compute_pem.py) und visualisiert Score-Zeitreihe, Recovery-Pattern-Verteilung, monatliche PEM-Burden und sport-bereinigte PEM-Rate vor/nach konfiguriertem Ereignisdatum.
@purpose.en  Reads from pem_evidence_scores (generated by compute_pem.py) and visualises score time series, recovery pattern distribution, monthly PEM burden and sport-adjusted PEM rate before/after the configured event date.
@method.de   Aggregation und Visualisierung der vorberechneten pem_evidence_scores-Tabelle; Aufgliederung nach Confidence-Level (confirmed = Reaktion gemessen, unabhängig vom Schwellenwert, vs. no_reaction_data = keine Messung vorhanden); Perioden-Vergleich relativ zu infection_date.
@method.en   Aggregation and visualisation of the pre-computed pem_evidence_scores table; breakdown by confidence level (confirmed = reaction was measured, regardless of threshold, vs. no_reaction_data = no measurement available); period comparison relative to infection_date.
@limits.de   Qualität abhängig vom upstream compute_pem.py-Output; PEM-Score ist heuristisch, nicht klinisch validiert; sport-bereinigte PEM-Rate erfordert ausreichende Trainingslog-Datenbasis.
@limits.en   Quality depends on upstream compute_pem.py output; PEM score is heuristic, not clinically validated; sport-adjusted PEM rate requires sufficient training log data.
@reads       pem_evidence_scores
@writes      analyses/postinfectious/pem_*.{md,png}
@refs        Task Force of the European Society of Cardiology and the North American Society of Pacing and Electrophysiology (1996). Heart rate variability: standards of measurement, physiological interpretation, and clinical use. Circulation, 93(5), 1043-1065. doi:10.1161/01.CIR.93.5.1043
             Shaffer F, Ginsberg JP (2017). An overview of heart rate variability metrics and norms. Frontiers in Public Health, 5:258. doi:10.3389/fpubh.2017.00258

Usage:
  python analyse_pem.py --plot
  python analyse_pem.py --plot --llm
  python analyse_pem.py --date-from 2023-01-01


@relevance.de  Ermöglicht die neurologische Analyse, essentiell für die Nervensystemdiagnostik
@relevance.en  Enables neurological analysis, essential for nervous system diagnostics
@prompt-classification  LLM:Analysis
@prompt.de             SYSTEM_PROMPT (de_only)
@prompt.en             -

@usage
    python analyse_pem.py
    python analyse_pem.py --help
    python analyse_pem.py --from 2024-01-01 --to 2024-12-31
"""

import argparse
from datetime import datetime
from pathlib import Path
import sys as _sys
_sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from health_config import Config as _Cfg, OWN_PERSON_ID
from modules.db import open_db
from modules.i18n import t, add_lang_arg, apply_lang_from_args

_cfg = _Cfg()
DB_PATH  = _cfg.db_path
OUT_DIR  = _cfg.analyses_dir / "postinfectious"

from modules.prompts.analysis_neurology import (
    SYSTEM_PROMPT_ANALYSE_PEM_DE as SYSTEM_PROMPT_DE,
    SYSTEM_PROMPT_ANALYSE_PEM_EN as SYSTEM_PROMPT_EN,
)


def _ts() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M")


def _load(conn, person: str, d0: str, d1: str) -> tuple[list, int]:
    """Gibt (confirmed_rows, n_no_reaction_data) zurück."""
    has_conf = any(
        r[1] == "confidence"
        for r in conn.execute("PRAGMA table_info(pem_evidence_scores)")
    )
    if has_conf:
        all_rows = conn.execute("""
            SELECT date, score, level, trig_score, react_score,
                   react_hrv_drop, best_lag, recovery_pattern, recovery_days,
                   trig_steps, trig_training, trig_hr_over_at, recovery_source,
                   confidence
            FROM pem_evidence_scores
            WHERE person=? AND date BETWEEN ? AND ?
            ORDER BY date
        """, (person, d0, d1)).fetchall()
        confirmed  = [r for r in all_rows if r[13] == "confirmed"]
        n_no_data  = len(all_rows) - len(confirmed)
        return confirmed, n_no_data
    # Fallback (alte DB ohne confidence)
    rows = conn.execute("""
        SELECT date, score, level, trig_score, react_score,
               react_hrv_drop, best_lag, recovery_pattern, recovery_days,
               trig_steps, trig_training, trig_hr_over_at, recovery_source,
               NULL
        FROM pem_evidence_scores
        WHERE person=? AND date BETWEEN ? AND ?
        ORDER BY date
    """, (person, d0, d1)).fetchall()
    return rows, 0


def _report(rows: list, infection_date: str | None) -> str:
    if not rows:
        return t("Keine PEM-Evidence-Score-Daten vorhanden. compute_pem.py zuerst ausführen.",
                 "No PEM evidence score data. Run compute_pem.py first.")

    total = len(rows)
    d_first, d_last = rows[0][0], rows[-1][0]

    by_level: dict[str, int] = {}
    for lvl in ["critical", "high", "moderate", "low", "none"]:
        by_level[lvl] = sum(1 for r in rows if r[2] == lvl)

    pattern_counts: dict[str, int] = {}
    source_counts:  dict[str, int] = {}
    for r in rows:
        if r[7]: pattern_counts[r[7]] = pattern_counts.get(r[7], 0) + 1
        if r[12]: source_counts[r[12]] = source_counts.get(r[12], 0) + 1

    n_trigger = sum(pattern_counts.values())

    lines = [
        t(f"## PEM Evidence Score — {d_first} bis {d_last}",
          f"## PEM Evidence Score — {d_first} to {d_last}"),
        "",
        t(f"Analysezeitraum: **{total} Tage**", f"Analysis period: **{total} days**"),
    ]
    if infection_date:
        lines.append(t(f"Infektionsdatum: **{infection_date}**",
                       f"Infection date: **{infection_date}**"))

    # ── Score-Verteilung ──────────────────────────────────────────────────────
    lines += ["", t("### Score-Verteilung (gesamt)", "### Score distribution (total)"), ""]
    for lvl in ["critical", "high", "moderate", "low", "none"]:
        n   = by_level[lvl]
        pct = round(n / total * 100)
        bar = "█" * (pct // 3)
        lines.append(f"  {lvl:<10} {n:>5} ({pct:>2}%)  {bar}")

    # ── Vor/Nach-Infektion ────────────────────────────────────────────────────
    if infection_date:
        pre  = [r for r in rows if r[0] < infection_date]
        post = [r for r in rows if r[0] >= infection_date]

        def _burden(subset, level_set):
            n_sig = sum(1 for r in subset if r[2] in level_set)
            return round(n_sig / len(subset) * 100, 1) if subset else 0.0

        lines += ["", t("### Vor/Nach-Infektion (Sport-bereinigt)", "### Pre/Post infection (sport-adjusted)"), ""]
        lines.append(f"  {'':20} {'Vor Infektion':>18}  {'Nach Infektion':>18}")
        lines.append(f"  {'':20} {'(' + str(len(pre)) + ' Tage)':>18}  {'(' + str(len(post)) + ' Tage)':>18}")
        lines.append(f"  {'-'*60}")
        for label, levels in [
            (t("Score ≥ moderate (≥30)", "Score ≥ moderate (≥30)"), {"moderate", "high", "critical"}),
            (t("Score ≥ high (≥50)",     "Score ≥ high (≥50)"),     {"high", "critical"}),
            (t("PEM-Pattern-Tage",        "PEM-pattern days"),        None),
        ]:
            if levels is None:
                pre_v  = sum(1 for r in pre  if r[7] == "pem_pattern")
                post_v = sum(1 for r in post if r[7] == "pem_pattern")
                pre_p  = round(pre_v  / len(pre)  * 100, 1) if pre  else 0
                post_p = round(post_v / len(post) * 100, 1) if post else 0
            else:
                pre_p  = _burden(pre,  levels)
                post_p = _burden(post, levels)
            arrow = "↑" if post_p > pre_p else ("↓" if post_p < pre_p else "=")
            lines.append(f"  {label:<30} {pre_p:>6.1f}%            {post_p:>6.1f}% {arrow}")

        # Kanalverfuegbarkeit: Der Score summiert die Reaktionskanaele, die an
        # einem Tag Daten haben. Hat der Vorher-Zeitraum ueberwiegend weniger
        # Kanaele (z. B. noch keine HRV), misst der Vergleich die Datenlage und
        # nicht die Belastbarkeit. Deshalb Abdeckung je Periode ausweisen und
        # zusaetzlich nur ab dem ersten Tag mit HRV-Reaktionsdaten vergleichen.
        def _hrv_share(subset):
            return round(sum(1 for r in subset if r[5] is not None) / len(subset) * 100, 1) if subset else 0.0
        lines.append(f"  {t('Tage mit HRV-Reaktionsdaten', 'Days with HRV reaction data'):<30} "
                     f"{_hrv_share(pre):>6.1f}%            {_hrv_share(post):>6.1f}%")
        hrv_dates = [r[0] for r in rows if r[5] is not None]
        if hrv_dates and pre and hrv_dates[0] > pre[0][0]:
            pre_cmp = [r for r in pre if r[0] >= hrv_dates[0]]
            if pre_cmp:
                lines.append(
                    f"  {t('Score ≥ moderate, nur ab ', 'Score ≥ moderate, only from ') + hrv_dates[0]:<30} "
                    f"{_burden(pre_cmp, {'moderate', 'high', 'critical'}):>6.1f}%            "
                    f"{_burden(post, {'moderate', 'high', 'critical'}):>6.1f}%  "
                    f"({len(pre_cmp)} {t('Tage vorher', 'days before')})")
        lines.append("")
        lines.append(t(
            "  ⚠ Kein Kausalnachweis: Unterschiedliche Kanalverfuegbarkeit, Geraetewechsel und "
            "zeitgleiche Ereignisse (s. klinischer Verlauf) koennen den Unterschied erklaeren.",
            "  ⚠ No causal evidence: differing channel availability, device changes and "
            "concurrent events (see clinical history) can explain the difference."))

    # ── Recovery-Pattern ─────────────────────────────────────────────────────
    if n_trigger:
        lines += ["", t("### Recovery-Pattern-Analyse (Belastungstage)",
                         "### Recovery pattern analysis (trigger days)"), ""]
        labels = {
            "sport_adaptation":  t("Sport-Adaptation  (Erholung <48h)  → Score÷2",
                                   "Sport adaptation  (recovery <48h)  → score÷2"),
            "supercompensation": t("Supercompensation (HRV > Baseline) → Score÷3",
                                   "Supercompensation (HRV > baseline) → score÷3"),
            "pem_pattern":       t("PEM-Muster        (≥3d unter 85%)  ⚠ PEM-verdächtig",
                                   "PEM pattern       (≥3d below 85%)  ⚠ suspicious"),
            "prolonged_drop":    t("Anhaltender Einbruch (≥3d unter 90%)",
                                   "Prolonged drop    (≥3d below 90%)"),
            "unclear":           t("Unklar            (Datenlücken oder gemischt)",
                                   "Unclear           (data gaps or mixed)"),
        }
        for pattern, label in labels.items():
            n   = pattern_counts.get(pattern, 0)
            pct = round(n / n_trigger * 100)
            bar = "█" * (pct // 5)
            lines.append(f"  {n:>5} ({pct:>2}%)  {bar:<16}  {label}")

        if source_counts:
            lines += ["", t("  Klassifikationsquelle:", "  Classification source:")]
            src_labels = {
                "hrv_rmssd_night": t("RMSSD Nacht (Referenzgeraet bzw. verfuegbares Wearable)",
                                     "Night RMSSD (reference device or available wearable)"),
                # Altlabel aus aelteren compute_pem-Laeufen: Geraet nicht belegbar,
                # daher keine Brustgurt-Behauptung mehr.
                "hrv_polar":       t("RMSSD Nacht (Altlabel, Geraet unbestimmt)",
                                     "Night RMSSD (legacy label, device undetermined)"),
                "hrv_apple_sdnn":  t("Apple Watch SDNN", "Apple Watch SDNN"),
                "rhr_proxy":       t("RHR-Proxy (Ruhepuls, invertiert)", "RHR proxy (resting HR, inverted)"),
                "no_data":         t("Keine Daten", "No data"),
            }
            for src, n in sorted(source_counts.items(), key=lambda x: -x[1]):
                label = src_labels.get(src, src)
                lines.append(f"    {n:>5} Tage  {label}")

    # ── Monatliche Burden ─────────────────────────────────────────────────────
    lines += ["", t("### Monatliche PEM-Burden (Score ≥30)", "### Monthly PEM burden (score ≥30)"), ""]
    monthly: dict[str, list] = {}
    for r in rows:
        ym = r[0][:7]
        monthly.setdefault(ym, []).append(r[1])
    for ym in sorted(monthly):
        vals     = monthly[ym]
        n_days   = len(vals)
        n_pem    = sum(1 for v in vals if v >= 30)
        burden   = round(n_pem / n_days * 100, 1)
        bar      = "█" * int(burden / 3)
        marker   = " ←" if infection_date and ym == infection_date[:7] else ""
        lines.append(f"  {ym}  {burden:>5.1f}%  {bar}{marker}")

    # ── Top-Tage ──────────────────────────────────────────────────────────────
    top = sorted([r for r in rows if r[1] >= 30], key=lambda r: -r[1])[:10]
    if top:
        lines += ["", t("### Top PEM-Tage (Score ≥30)", "### Top PEM days (score ≥30)"), ""]
        for r in top:
            hrv_str = f"HRV−{r[5]:.0f}%" if r[5] else "HRV—"
            pat     = f"[{r[7]}]" if r[7] else ""
            src     = f"/{r[12]}" if r[12] else ""
            inf_tag = " ◀POST" if infection_date and r[0] >= infection_date else ""
            lines.append(f"  {r[0]}  score={r[1]:>3}  [{r[2]}]  "
                         f"trig={r[3]} react={r[4]} lag+{r[6]}d  {hrv_str}  {pat}{src}{inf_tag}")

    return "\n".join(lines)


def _report_llm_summary(rows: list, infection_date: str | None) -> str:
    """Kompakter Report für LLM — ohne vollständige Monatsreihe."""
    if not rows:
        return "Keine Daten."
    total = len(rows)
    pre   = [r for r in rows if not infection_date or r[0] < infection_date]
    post  = [r for r in rows if infection_date and r[0] >= infection_date]

    def burden(subset, min_score):
        n = sum(1 for r in subset if r[1] >= min_score)
        return round(n / len(subset) * 100, 1) if subset else 0.0

    pat_counts: dict[str, int] = {}
    src_counts: dict[str, int] = {}
    for r in rows:
        if r[7]: pat_counts[r[7]] = pat_counts.get(r[7], 0) + 1
        if r[12]: src_counts[r[12]] = src_counts.get(r[12], 0) + 1

    # Letzte 24 Monate Burden
    from collections import defaultdict
    monthly: dict[str, list] = defaultdict(list)
    for r in rows:
        monthly[r[0][:7]].append(r[1])
    recent_months = sorted(monthly)[-24:]

    lines = [
        f"PEM Evidence Score — {rows[0][0]} bis {rows[-1][0]}",
        f"Infektionsdatum: {infection_date or 'unbekannt'}",
        f"Analysezeitraum: {total} Tage",
        "",
        "Score-Verteilung (sport-bereinigt):",
        f"  Score ≥50 (high/critical): {sum(1 for r in rows if r[1] >= 50)} Tage",
        f"  Score ≥30 (moderate+):     {sum(1 for r in rows if r[1] >= 30)} Tage",
        "",
        "Vor / Nach Infektion:",
        f"  Score ≥30: {burden(pre, 30)}% vor → {burden(post, 30)}% nach",
        f"  Score ≥50: {burden(pre, 50)}% vor → {burden(post, 50)}% nach",
        f"  PEM-Pattern: {burden(pre, 1) if False else round(sum(1 for r in pre if r[7]=='pem_pattern')/len(pre)*100,1) if pre else 0}% vor"
        f" → {round(sum(1 for r in post if r[7]=='pem_pattern')/len(post)*100,1) if post else 0}% nach",
        "",
        "Recovery-Pattern (alle Belastungstage):",
    ] + [f"  {pat}: {n}" for pat, n in sorted(pat_counts.items(), key=lambda x: -x[1])] + [
        "",
        "Klassifikationsquellen:",
    ] + [f"  {src}: {n} Tage" for src, n in sorted(src_counts.items(), key=lambda x: -x[1])] + [
        "",
        "Top PEM-Tage (score ≥30):",
    ] + [
        f"  {r[0]} score={r[1]} [{r[2]}] trig={r[3]} react={r[4]}"
        f" lag+{r[6]}d HRV{f'-{r[5]:.0f}%' if r[5] else '—'}"
        f" [{r[7]}]/{r[12]}"
        + (" ◀POST" if infection_date and r[0] >= infection_date else "")
        for r in sorted([r for r in rows if r[1] >= 30], key=lambda r: -r[1])[:10]
    ] + [
        "",
        "PEM-Burden letzte 24 Monate (Score ≥30):",
    ] + [
        f"  {ym}: {round(sum(1 for v in monthly[ym] if v >= 30)/len(monthly[ym])*100,1)}%"
        + (" ←INFEKTION" if infection_date and ym == infection_date[:7] else "")
        + (" ◀POST" if infection_date and ym > infection_date[:7] else "")
        for ym in recent_months
    ]
    return "\n".join(lines)


def _plot(rows: list, infection_date: str | None, out_dir: Path) -> "Path | None":
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
    except ImportError:
        return None

    if not rows:
        return None

    BG   = "#1e1e2e"
    FG   = "#cdd6f4"
    ACC1 = "#f38ba8"   # critical/high — rot
    ACC2 = "#fab387"   # moderate — orange
    ACC3 = "#a6e3a1"   # sport adaptation — grün
    ACC4 = "#89b4fa"   # score line — blau

    dates  = [datetime.strptime(r[0], "%Y-%m-%d") for r in rows]
    scores = [r[1] for r in rows]
    levels = [r[2] for r in rows]
    patterns = [r[7] for r in rows]

    fig, axes = plt.subplots(3, 1, figsize=(14, 11), facecolor=BG)
    fig.suptitle(t("PEM Evidence Score — Sport-bereinigt",
                   "PEM Evidence Score — Sport-adjusted"),
                 color=FG, fontsize=13, fontweight="bold")

    for ax in axes:
        ax.set_facecolor(BG)
        ax.tick_params(colors=FG)
        for sp in ax.spines.values():
            sp.set_color("#45475a")

    inf_dt = datetime.strptime(infection_date, "%Y-%m-%d") if infection_date else None

    # ── Subplot 1: Score-Zeitreihe ────────────────────────────────────────────
    ax1 = axes[0]
    colors = []
    for lvl, pat in zip(levels, patterns):
        if pat in ("sport_adaptation", "supercompensation"):
            colors.append(ACC3)
        elif lvl in ("critical", "high"):
            colors.append(ACC1)
        elif lvl == "moderate":
            colors.append(ACC2)
        else:
            colors.append("#585b70")
    ax1.bar(dates, scores, color=colors, width=1.0, alpha=0.8)
    # 30-Tage gleitender Mittelwert
    window = 30
    if len(scores) >= window:
        ma = []
        for i in range(len(scores)):
            lo = max(0, i - window // 2)
            hi = min(len(scores), i + window // 2 + 1)
            ma.append(sum(scores[lo:hi]) / (hi - lo))
        ax1.plot(dates, ma, color=ACC4, linewidth=1.5, label=t("30d-Mittel", "30d avg"))
    if inf_dt:
        ax1.axvline(inf_dt, color=ACC1, linestyle="--", linewidth=1.2,
                    label=t(f"Infektion {infection_date}", f"Infection {infection_date}"))
    ax1.axhline(30, color=ACC2, linestyle=":", linewidth=0.8, alpha=0.6)
    ax1.axhline(50, color=ACC1, linestyle=":", linewidth=0.8, alpha=0.6)
    ax1.set_ylabel(t("PEM Score", "PEM score"), color=FG)
    ax1.set_title(t("Score-Zeitreihe (grün = Sport-erklärbar)",
                    "Score over time (green = sport-explained)"), color=FG, fontsize=10)
    if ax1.get_legend_handles_labels()[0]:
        ax1.legend(facecolor="#313244", labelcolor=FG, fontsize=8)
    ax1.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    ax1.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    plt.setp(ax1.xaxis.get_majorticklabels(), rotation=30, ha="right")

    # ── Subplot 2: Recovery-Pattern Stacked-Bar monatlich ────────────────────
    ax2 = axes[1]
    monthly_pat: dict[str, dict[str, int]] = {}
    for r in rows:
        ym  = r[0][:7]
        pat = r[7] or "no_trigger"
        monthly_pat.setdefault(ym, {}).setdefault(pat, 0)
        monthly_pat[ym][pat] += 1

    yms  = sorted(monthly_pat)
    xpos = [datetime.strptime(ym + "-15", "%Y-%m-%d") for ym in yms]
    pat_colors = {
        "supercompensation": ACC3,
        "sport_adaptation":  "#74c7ec",
        "pem_pattern":       ACC1,
        "prolonged_drop":    ACC2,
        "unclear":           "#585b70",
        "no_trigger":        "#313244",
    }
    bottom = [0] * len(yms)
    for pat, col in pat_colors.items():
        vals = [monthly_pat[ym].get(pat, 0) for ym in yms]
        ax2.bar(xpos, vals, bottom=bottom, color=col, width=20,
                label=pat.replace("_", " "), alpha=0.9)
        bottom = [b + v for b, v in zip(bottom, vals)]
    if inf_dt:
        ax2.axvline(inf_dt, color=ACC1, linestyle="--", linewidth=1.2)
    ax2.set_ylabel(t("Tage", "Days"), color=FG)
    ax2.set_title(t("Recovery-Pattern pro Monat", "Recovery pattern per month"),
                  color=FG, fontsize=10)
    ax2.legend(facecolor="#313244", labelcolor=FG, fontsize=7,
               loc="upper left", ncol=3)
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    ax2.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    plt.setp(ax2.xaxis.get_majorticklabels(), rotation=30, ha="right")

    # ── Subplot 3: Monatliche PEM-Burden (Score ≥30) ──────────────────────────
    ax3 = axes[2]
    burden_x, burden_y, burden_colors = [], [], []
    for ym in yms:
        d_ym = datetime.strptime(ym + "-15", "%Y-%m-%d")
        ym_rows = [r for r in rows if r[0][:7] == ym]
        burden  = sum(1 for r in ym_rows if r[1] >= 30) / len(ym_rows) * 100 if ym_rows else 0
        burden_x.append(d_ym)
        burden_y.append(burden)
        burden_colors.append(ACC1 if (inf_dt and d_ym >= inf_dt) else ACC4)
    ax3.bar(burden_x, burden_y, color=burden_colors, width=20, alpha=0.85)
    if inf_dt:
        ax3.axvline(inf_dt, color=ACC1, linestyle="--", linewidth=1.2)
    ax3.set_ylabel(t("Burden %", "Burden %"), color=FG)
    ax3.set_title(t("Monatl. PEM-Burden (Score ≥30, blau = vor Inf., rot = nach Inf.)",
                    "Monthly PEM burden (score ≥30, blue = pre, red = post infection)"),
                  color=FG, fontsize=10)
    ax3.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    ax3.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    plt.setp(ax3.xaxis.get_majorticklabels(), rotation=30, ha="right")

    plt.tight_layout(rect=[0, 0, 1, 0.97])
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"pem_evidence_{_ts()}.png"
    fig.savefig(str(path), dpi=130, bbox_inches="tight", facecolor=BG)
    plt.close()
    print(t(f"Plot: {path}", f"Plot: {path}"))
    return path


def _run_llm(report: str) -> str:
    try:
        from modules.llm import call_llm
        print(t("\nLLM analysiert ...", "\nLLM analysing ..."))
        return call_llm(report, system=t(SYSTEM_PROMPT_DE, SYSTEM_PROMPT_EN), max_tokens=8000)
    except Exception as e:
        print(t(f"LLM nicht verfügbar: {e}", f"LLM not available: {e}"))
        return ""


def _save(report: str, llm_text: str = "") -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"pem_evidence_{_ts()}.md"
    content = report
    if llm_text:
        content += f"\n\n---\n\n{llm_text}"
    path.write_text(content, encoding="utf-8")
    print(t(f"Bericht: {path}", f"Report: {path}"))
    return path


def main():
    parser = argparse.ArgumentParser(
        description=t("PEM Evidence Score analysieren", "Analyse PEM evidence scores"))
    parser.add_argument("--person",    default=None)
    parser.add_argument("--date-from", "--from", dest="date_from", default=None)
    parser.add_argument("--date-to", "--to", dest="date_to", default=None)
    parser.add_argument("--plot",      action="store_true")
    parser.add_argument("--llm",       action="store_true")
    parser.add_argument("--no-llm",    dest="no_llm", action="store_true")
    add_lang_arg(parser)
    args = parser.parse_args()
    apply_lang_from_args(args)

    conn   = open_db()
    person = args.person or OWN_PERSON_ID

    # Prüfe ob Tabelle existiert
    tables = {r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type IN ('table','view')")}
    if "pem_evidence_scores" not in tables:
        print(t("pem_evidence_scores nicht gefunden — bitte zuerst compute_pem.py ausführen.",
                "pem_evidence_scores not found — run compute_pem.py first."))
        return

    d0 = args.date_from or _cfg.data_start or "2017-01-01"
    d1 = args.date_to   or datetime.today().strftime("%Y-%m-%d")

    rows, n_no_data = _load(conn, person, d0, d1)
    infection_date = _cfg.infection_date

    if n_no_data:
        print(t(f"Hinweis: {n_no_data} Tage ohne jede HRV/RHR/Schlaf/Symptom-Messung "
                f"(no_reaction_data) ausgeblendet — nicht zu verwechseln mit Tagen, an "
                f"denen gemessen wurde und keine Reaktion auftrat (die bleiben enthalten).",
                f"Note: {n_no_data} days with no HRV/RHR/sleep/symptom measurement at all "
                f"(no_reaction_data) excluded — not to be confused with days that were "
                f"measured and showed no reaction (those remain included)."))

    report  = _report(rows, infection_date)
    print(report)

    plot_path = None
    if args.plot:
        plot_path = _plot(rows, infection_date, OUT_DIR)

    llm_text = ""
    if args.llm and not args.no_llm and rows:
        print(t("OpenRouter analysiert PEM-Evidence-Score ...",
                "OpenRouter analysing PEM evidence score ..."))
        bericht_llm = _report_llm_summary(rows, infection_date)
        llm_text = _run_llm(bericht_llm)

    if plot_path or llm_text:
        _save(report, llm_text)

    conn.close()


if __name__ == "__main__":
    main()
