# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Kyoro-HealthHub contributors
"""
llm.py — LLM/VLM-Brücke

@tier        infrastructure
@refs        Muneer, A., Zhang, K., Hamdi, I., Qureshi, R., Waqas, M., Fouad, S., Ali, H., Anwar, S.M., Wu, J.
             (2026). Foundation models in biomedical imaging: turning hype
             into reality. Nature Biomedical Engineering, 10:1557-1575. doi:10.1038/s41551-026-01762-z
             (REAL-FM framework — Grundlage fuer _GROUNDING_SUFFIX/require_grounding und
             ai_label()/label_output unten: Kalibrierung/Unsicherheitsangabe sowie die
             KI-Kennzeichnungspflicht aus openspec/specs/ethics-enforcement/spec.md fehlten
             projektweit bis auf ein einzelnes Skript)
@purpose.de  Bietet eine einheitliche Schnittstelle für LLM- und VLM-Aufrufe.
             delegiert an den konfigurierten Provider in health_config.json.
@purpose.en  Provides a unified interface for LLM and VLM calls.
             Delegates to the configured provider in health_config.json.
@method.de   Text-Aufrufe verwenden den Provider unter "llm" in health_config.json.
             Vision-Aufrufe verwenden den Provider unter "vlm" (fällt auf "llm" zurück,
             falls "vlm" nicht konfiguriert). Unterstützt Text-Only und Multi-Modal-Prompts.
@method.en   Text calls use the provider under "llm" in health_config.json.
             Vision calls use the provider under "vlm" (falls back to "llm" provider
             if "vlm" is absent). Supports text-only and multi-modal prompts.
@reads       ~/.config/kyoro/health_config.json (Provider-Konfiguration)
@writes      Keine Tabellen (gibt LLM-Antworten zurück)
@limits.de   Abhaengig vom konfigurierten LLM-Provider. Keine Garantie fuer Antwortqualitaet oder Datenschutz.

@relevance.de  Bietet Sprachmodell-Schnittstellen, essentiell für die KI-Integration
@relevance.en  Provides language model interfaces, essential for AI integration
@limits.en   Dependent on configured LLM provider. No guarantee of response quality or data privacy.
@usage
    from modules.llm import call_llm
    response = call_llm(prompt, system="You are …")
    import base64
    b64 = base64.b64encode(Path("scan.jpg").read_bytes()).decode()
    response = call_llm(prompt, image_b64=b64, image_mime="image/jpeg")
"""
from __future__ import annotations

import base64
import contextlib
import io
import sys
import tempfile
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from health_config import Config
from modules.i18n import t
from utils.llm_provider import LLMProvider

_cfg = Config()
_text_provider_instance: LLMProvider | None = None
_vision_provider_instance: LLMProvider | None = None

# Angehängt an jeden System-Prompt (sofern nicht explizit abgewählt) — macht
# jede Aussage nachprüfbar statt nur plausibel klingend, siehe REAL-FM-
# Framework (Nature Biomedical Engineering, Aug 2026): Kalibrierung/
# Unsicherheitsangabe fehlte projektweit bis auf ein einzelnes Skript.
# Kurz gehalten, um die Antwortlänge nicht unnötig aufzublähen (längere
# Begründungsketten korrelieren laut Paper mit MEHR, nicht weniger Fehlern).
_GROUNDING_SUFFIX = (
    "\n\nFür jede zentrale Aussage: markiere kurz eine Konfidenz "
    "(hoch/mittel/niedrig) und nenne den konkreten Datenpunkt, auf dem sie "
    "beruht. Aussagen ohne Rückführung auf einen Datenpunkt explizit als "
    "eigene Einschätzung kennzeichnen, nicht als Tatsache formulieren."
    "\n\nFor each key statement: briefly mark a confidence level "
    "(high/medium/low) and name the concrete data point it's based on. "
    "Label statements that can't be traced to a data point as your own "
    "assessment, not as fact."
)

# openspec/specs/ethics-enforcement/spec.md, "Labeling of AI-generated
# output": SHALL be clearly labeled everywhere it is displayed. Applied by
# default at the return-value level here rather than per-caller, since a
# per-file audit found most analysis scripts producing unlabeled output
# despite the requirement (only health_query.py implemented it by hand).
_AI_LABEL_DE = "*KI-generiert von {model} am {ts} | Nicht für klinische Diagnose*"
_AI_LABEL_EN = "*AI-generated by {model} on {ts} | Not for clinical diagnosis*"


def grounding_suffix() -> str:
    """Public accessor for _GROUNDING_SUFFIX, for callers with their own LLM
    call path (e.g. health_query.py's ask_llm(), which talks to its provider
    directly instead of through call_llm()) that still want the calibration/
    grounding instruction applied."""
    return _GROUNDING_SUFFIX


def ai_label(provider_name: str | None = None) -> str:
    """Standard AI-generated disclaimer for any surface that displays LLM
    output outside call_llm()'s own label_output=True default (e.g. a
    caller with its own HTTP request instead of going through call_llm()).
    provider_name defaults to the configured text provider."""
    name = provider_name or _text_provider().name
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    return t(_AI_LABEL_DE, _AI_LABEL_EN).format(model=name, ts=ts)


def _text_provider() -> LLMProvider:
    global _text_provider_instance
    if _text_provider_instance is None:
        _text_provider_instance = LLMProvider.from_config(_cfg._cfg)
    return _text_provider_instance


def _vision_provider() -> LLMProvider:
    global _vision_provider_instance
    if _vision_provider_instance is None:
        raw = _cfg._cfg
        if "vlm" in raw:
            _vision_provider_instance = LLMProvider.from_config({"llm": raw["vlm"]})
        else:
            _vision_provider_instance = LLMProvider.from_config(raw)
    return _vision_provider_instance


def call_llm(
    prompt: str,
    *,
    system: str | None = None,
    model: str | None = None,   # ignored — model comes from config
    image_b64: str | None = None,
    image_mime: str = "image/jpeg",
    max_tokens: int = 2000,
    temperature: float = 0.1,   # note: temperature is set per-provider in llm_provider.py
    require_grounding: bool = True,
    label_output: bool = True,
) -> str:
    """Send a prompt to the configured LLM or VLM provider.

    require_grounding: appends _GROUNDING_SUFFIX to the system prompt
    (default True — most callers produce clinical claims that should be
    calibrated/traceable). Pass False for calls where confidence/source
    markers would be inappropriate (e.g. short structured/non-clinical
    outputs).

    label_output: appends ai_label() to the returned text (default True —
    openspec/specs/ethics-enforcement/spec.md requires LLM output be
    labeled as AI-generated wherever displayed). Pass False when the
    return value is parsed structurally instead of shown as prose (JSON
    extraction, regex-matched triage markers) — label at the point it is
    actually rendered to a person instead."""
    if require_grounding:
        system = (system or "") + _GROUNDING_SUFFIX
    if image_b64:
        provider = _vision_provider()
        ext = {"image/jpeg": ".jpg", "image/png": ".png",
               "image/webp": ".webp"}.get(image_mime, ".jpg")
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            tmp.write(base64.standard_b64decode(image_b64))
            tmp_path = Path(tmp.name)
        try:
            text = provider.vision(tmp_path, prompt, max_tokens=max_tokens)
        finally:
            tmp_path.unlink(missing_ok=True)
        return text + "\n\n" + ai_label(provider.name) if label_output else text
    else:
        text = _text_provider().chat(system or "", prompt, max_tokens=max_tokens)
        return text + "\n\n" + ai_label(_text_provider().name) if label_output else text


class _Tee(io.TextIOBase):
    def __init__(self, real):
        self.real = real
        self.buf = io.StringIO()

    def write(self, s):
        self.buf.write(s)
        return self.real.write(s)

    def flush(self):
        self.real.flush()


@contextlib.contextmanager
def capture_stdout():
    """Context manager for console-only scripts (documented @writes: stdout only)
    that still want an LLM commentary: everything printed inside the `with` block
    keeps appearing live on the terminal AND is captured, so it can be handed to
    call_llm() as the report text afterwards. Replaces a _Tee class that used to
    be duplicated verbatim in analyse_product_exposures.py and analyse_allergens.py.

    Usage:
        with capture_stdout() as buf:
            report_summary(conn, person)
            report_daily(conn, person)
        llm_text = call_llm(buf.getvalue(), system=SYSTEM_PROMPT)
    """
    tee = _Tee(sys.stdout)
    old_stdout = sys.stdout
    sys.stdout = tee
    try:
        yield tee.buf
    finally:
        sys.stdout = old_stdout
